/*
ScrapeBadger API

Testing LinkedInAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package scrapebadger

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/scrape-badger/scrapebadger-go"
)

func Test_scrapebadger_LinkedInAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test LinkedInAPIService LinkedinGetACompanySJobPostings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var companyId string

		resp, httpRes, err := apiClient.LinkedInAPI.LinkedinGetACompanySJobPostings(context.Background(), companyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LinkedInAPIService LinkedinGetACourse", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var courseSlug string

		resp, httpRes, err := apiClient.LinkedInAPI.LinkedinGetACourse(context.Background(), courseSlug).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LinkedInAPIService LinkedinGetAPublicArticle", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var articleSlug string

		resp, httpRes, err := apiClient.LinkedInAPI.LinkedinGetAPublicArticle(context.Background(), articleSlug).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LinkedInAPIService LinkedinGetAPublicPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var postSlug string

		resp, httpRes, err := apiClient.LinkedInAPI.LinkedinGetAPublicPost(context.Background(), postSlug).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LinkedInAPIService LinkedinGetCompany", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var universalName string

		resp, httpRes, err := apiClient.LinkedInAPI.LinkedinGetCompany(context.Background(), universalName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LinkedInAPIService LinkedinGetJobDetail", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var jobId string

		resp, httpRes, err := apiClient.LinkedInAPI.LinkedinGetJobDetail(context.Background(), jobId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LinkedInAPIService LinkedinGetPublicProfile", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var publicId string

		resp, httpRes, err := apiClient.LinkedInAPI.LinkedinGetPublicProfile(context.Background(), publicId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LinkedInAPIService LinkedinGetSchool", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var universalName string

		resp, httpRes, err := apiClient.LinkedInAPI.LinkedinGetSchool(context.Background(), universalName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LinkedInAPIService LinkedinLinkedinScraperHealthCheck", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.LinkedInAPI.LinkedinLinkedinScraperHealthCheck(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LinkedInAPIService LinkedinLinkedinScraperHealthCheckHead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.LinkedInAPI.LinkedinLinkedinScraperHealthCheckHead(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LinkedInAPIService LinkedinSearchLinkedinJobs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.LinkedInAPI.LinkedinSearchLinkedinJobs(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LinkedInAPIService LinkedinSuggestLocationGeoIds", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.LinkedInAPI.LinkedinSuggestLocationGeoIds(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
