/*
ScrapeBadger API

Testing IdealistaAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package scrapebadger

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/scrape-badger/scrapebadger-go"
)

func Test_scrapebadger_IdealistaAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test IdealistaAPIService IdealistaAgencyByPhone", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var phone string

		resp, httpRes, err := apiClient.IdealistaAPI.IdealistaAgencyByPhone(context.Background(), phone).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdealistaAPIService IdealistaAgencyProfileListings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var shortName string

		resp, httpRes, err := apiClient.IdealistaAPI.IdealistaAgencyProfileListings(context.Background(), shortName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdealistaAPIService IdealistaGetListingEngagementStats", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var propertyCode string

		resp, httpRes, err := apiClient.IdealistaAPI.IdealistaGetListingEngagementStats(context.Background(), propertyCode).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdealistaAPIService IdealistaGetPropertyDetail", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var propertyCode string

		resp, httpRes, err := apiClient.IdealistaAPI.IdealistaGetPropertyDetail(context.Background(), propertyCode).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdealistaAPIService IdealistaIdealistaScraperHealthCheck", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.IdealistaAPI.IdealistaIdealistaScraperHealthCheck(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdealistaAPIService IdealistaIdealistaScraperHealthCheckHead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.IdealistaAPI.IdealistaIdealistaScraperHealthCheckHead(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdealistaAPIService IdealistaListMarkets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.IdealistaAPI.IdealistaListMarkets(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdealistaAPIService IdealistaResolveLocations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.IdealistaAPI.IdealistaResolveLocations(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdealistaAPIService IdealistaSearchAllBeatsResultCap", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.IdealistaAPI.IdealistaSearchAllBeatsResultCap(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdealistaAPIService IdealistaSearchListings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.IdealistaAPI.IdealistaSearchListings(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
