/*
ScrapeBadger API

Testing ChatGPTAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package scrapebadger

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/scrape-badger/scrapebadger-go"
)

func Test_scrapebadger_ChatGPTAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ChatGPTAPIService ChatgptAskChatgptAQuestion", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ChatGPTAPI.ChatgptAskChatgptAQuestion(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChatGPTAPIService ChatgptAskChatgptAQuestionPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ChatGPTAPI.ChatgptAskChatgptAQuestionPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChatGPTAPIService ChatgptChatgptScraperHealthCheck", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ChatGPTAPI.ChatgptChatgptScraperHealthCheck(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChatGPTAPIService ChatgptChatgptScraperHealthCheckHead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ChatGPTAPI.ChatgptChatgptScraperHealthCheckHead(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChatGPTAPIService ChatgptListChatgptModels", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ChatGPTAPI.ChatgptListChatgptModels(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChatGPTAPIService ChatgptMeasureABrandSVisibilityInAChatgptAnswer", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ChatGPTAPI.ChatgptMeasureABrandSVisibilityInAChatgptAnswer(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ChatGPTAPIService ChatgptMeasureABrandSVisibilityInAChatgptAnswerPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ChatGPTAPI.ChatgptMeasureABrandSVisibilityInAChatgptAnswerPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
