/*
ScrapeBadger API

Testing ImmobiliareAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package scrapebadger

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/scrape-badger/scrapebadger-go"
)

func Test_scrapebadger_ImmobiliareAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ImmobiliareAPIService ImmobiliareGetAgencyProfile", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agencyId int32

		resp, httpRes, err := apiClient.ImmobiliareAPI.ImmobiliareGetAgencyProfile(context.Background(), agencyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ImmobiliareAPIService ImmobiliareGetAnAgencySListings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var agencyId int32

		resp, httpRes, err := apiClient.ImmobiliareAPI.ImmobiliareGetAnAgencySListings(context.Background(), agencyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ImmobiliareAPIService ImmobiliareGetListingDetail", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var listingId int32

		resp, httpRes, err := apiClient.ImmobiliareAPI.ImmobiliareGetListingDetail(context.Background(), listingId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ImmobiliareAPIService ImmobiliareImmobiliareScraperHealthCheck", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ImmobiliareAPI.ImmobiliareImmobiliareScraperHealthCheck(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ImmobiliareAPIService ImmobiliareImmobiliareScraperHealthCheckHead", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ImmobiliareAPI.ImmobiliareImmobiliareScraperHealthCheckHead(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ImmobiliareAPIService ImmobiliareListFilterEnums", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ImmobiliareAPI.ImmobiliareListFilterEnums(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ImmobiliareAPIService ImmobiliareListMarkets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ImmobiliareAPI.ImmobiliareListMarkets(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ImmobiliareAPIService ImmobiliareLocationAutocomplete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ImmobiliareAPI.ImmobiliareLocationAutocomplete(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ImmobiliareAPIService ImmobiliarePriceMTimeSeries", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ImmobiliareAPI.ImmobiliarePriceMTimeSeries(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ImmobiliareAPIService ImmobiliareSearchListings", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ImmobiliareAPI.ImmobiliareSearchListings(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
