/*
ScrapeBadger API

Unified credit-based scraping API. https://docs.scrapebadger.com

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package scrapebadger

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StreamMonitorCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StreamMonitorCreate{}

// StreamMonitorCreate Create stream monitor request.
type StreamMonitorCreate struct {
	Name string `json:"name"`
	Usernames []string `json:"usernames"`
	WebhookUrl NullableString `json:"webhook_url,omitempty"`
	WebhookSecret NullableString `json:"webhook_secret,omitempty"`
	FilterTypes []string `json:"filter_types,omitempty"`
}

type _StreamMonitorCreate StreamMonitorCreate

// NewStreamMonitorCreate instantiates a new StreamMonitorCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStreamMonitorCreate(name string, usernames []string) *StreamMonitorCreate {
	this := StreamMonitorCreate{}
	this.Name = name
	this.Usernames = usernames
	return &this
}

// NewStreamMonitorCreateWithDefaults instantiates a new StreamMonitorCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStreamMonitorCreateWithDefaults() *StreamMonitorCreate {
	this := StreamMonitorCreate{}
	return &this
}

// GetName returns the Name field value
func (o *StreamMonitorCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *StreamMonitorCreate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *StreamMonitorCreate) SetName(v string) {
	o.Name = v
}

// GetUsernames returns the Usernames field value
func (o *StreamMonitorCreate) GetUsernames() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Usernames
}

// GetUsernamesOk returns a tuple with the Usernames field value
// and a boolean to check if the value has been set.
func (o *StreamMonitorCreate) GetUsernamesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Usernames, true
}

// SetUsernames sets field value
func (o *StreamMonitorCreate) SetUsernames(v []string) {
	o.Usernames = v
}

// GetWebhookUrl returns the WebhookUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StreamMonitorCreate) GetWebhookUrl() string {
	if o == nil || IsNil(o.WebhookUrl.Get()) {
		var ret string
		return ret
	}
	return *o.WebhookUrl.Get()
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StreamMonitorCreate) GetWebhookUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WebhookUrl.Get(), o.WebhookUrl.IsSet()
}

// HasWebhookUrl returns a boolean if a field has been set.
func (o *StreamMonitorCreate) HasWebhookUrl() bool {
	if o != nil && o.WebhookUrl.IsSet() {
		return true
	}

	return false
}

// SetWebhookUrl gets a reference to the given NullableString and assigns it to the WebhookUrl field.
func (o *StreamMonitorCreate) SetWebhookUrl(v string) {
	o.WebhookUrl.Set(&v)
}
// SetWebhookUrlNil sets the value for WebhookUrl to be an explicit nil
func (o *StreamMonitorCreate) SetWebhookUrlNil() {
	o.WebhookUrl.Set(nil)
}

// UnsetWebhookUrl ensures that no value is present for WebhookUrl, not even an explicit nil
func (o *StreamMonitorCreate) UnsetWebhookUrl() {
	o.WebhookUrl.Unset()
}

// GetWebhookSecret returns the WebhookSecret field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StreamMonitorCreate) GetWebhookSecret() string {
	if o == nil || IsNil(o.WebhookSecret.Get()) {
		var ret string
		return ret
	}
	return *o.WebhookSecret.Get()
}

// GetWebhookSecretOk returns a tuple with the WebhookSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StreamMonitorCreate) GetWebhookSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WebhookSecret.Get(), o.WebhookSecret.IsSet()
}

// HasWebhookSecret returns a boolean if a field has been set.
func (o *StreamMonitorCreate) HasWebhookSecret() bool {
	if o != nil && o.WebhookSecret.IsSet() {
		return true
	}

	return false
}

// SetWebhookSecret gets a reference to the given NullableString and assigns it to the WebhookSecret field.
func (o *StreamMonitorCreate) SetWebhookSecret(v string) {
	o.WebhookSecret.Set(&v)
}
// SetWebhookSecretNil sets the value for WebhookSecret to be an explicit nil
func (o *StreamMonitorCreate) SetWebhookSecretNil() {
	o.WebhookSecret.Set(nil)
}

// UnsetWebhookSecret ensures that no value is present for WebhookSecret, not even an explicit nil
func (o *StreamMonitorCreate) UnsetWebhookSecret() {
	o.WebhookSecret.Unset()
}

// GetFilterTypes returns the FilterTypes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StreamMonitorCreate) GetFilterTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.FilterTypes
}

// GetFilterTypesOk returns a tuple with the FilterTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StreamMonitorCreate) GetFilterTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.FilterTypes) {
		return nil, false
	}
	return o.FilterTypes, true
}

// HasFilterTypes returns a boolean if a field has been set.
func (o *StreamMonitorCreate) HasFilterTypes() bool {
	if o != nil && !IsNil(o.FilterTypes) {
		return true
	}

	return false
}

// SetFilterTypes gets a reference to the given []string and assigns it to the FilterTypes field.
func (o *StreamMonitorCreate) SetFilterTypes(v []string) {
	o.FilterTypes = v
}

func (o StreamMonitorCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StreamMonitorCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["usernames"] = o.Usernames
	if o.WebhookUrl.IsSet() {
		toSerialize["webhook_url"] = o.WebhookUrl.Get()
	}
	if o.WebhookSecret.IsSet() {
		toSerialize["webhook_secret"] = o.WebhookSecret.Get()
	}
	if o.FilterTypes != nil {
		toSerialize["filter_types"] = o.FilterTypes
	}
	return toSerialize, nil
}

func (o *StreamMonitorCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"usernames",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStreamMonitorCreate := _StreamMonitorCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStreamMonitorCreate)

	if err != nil {
		return err
	}

	*o = StreamMonitorCreate(varStreamMonitorCreate)

	return err
}

type NullableStreamMonitorCreate struct {
	value *StreamMonitorCreate
	isSet bool
}

func (v NullableStreamMonitorCreate) Get() *StreamMonitorCreate {
	return v.value
}

func (v *NullableStreamMonitorCreate) Set(val *StreamMonitorCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableStreamMonitorCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableStreamMonitorCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStreamMonitorCreate(val *StreamMonitorCreate) *NullableStreamMonitorCreate {
	return &NullableStreamMonitorCreate{value: val, isSet: true}
}

func (v NullableStreamMonitorCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStreamMonitorCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


