/*
ScrapeBadger API

Unified credit-based scraping API. https://docs.scrapebadger.com

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package scrapebadger

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebhookCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookCreate{}

// WebhookCreate Configure webhook on a monitor.
type WebhookCreate struct {
	MonitorId string `json:"monitor_id"`
	Url string `json:"url"`
	Secret NullableString `json:"secret,omitempty"`
}

type _WebhookCreate WebhookCreate

// NewWebhookCreate instantiates a new WebhookCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookCreate(monitorId string, url string) *WebhookCreate {
	this := WebhookCreate{}
	this.MonitorId = monitorId
	this.Url = url
	return &this
}

// NewWebhookCreateWithDefaults instantiates a new WebhookCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookCreateWithDefaults() *WebhookCreate {
	this := WebhookCreate{}
	return &this
}

// GetMonitorId returns the MonitorId field value
func (o *WebhookCreate) GetMonitorId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MonitorId
}

// GetMonitorIdOk returns a tuple with the MonitorId field value
// and a boolean to check if the value has been set.
func (o *WebhookCreate) GetMonitorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MonitorId, true
}

// SetMonitorId sets field value
func (o *WebhookCreate) SetMonitorId(v string) {
	o.MonitorId = v
}

// GetUrl returns the Url field value
func (o *WebhookCreate) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhookCreate) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhookCreate) SetUrl(v string) {
	o.Url = v
}

// GetSecret returns the Secret field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookCreate) GetSecret() string {
	if o == nil || IsNil(o.Secret.Get()) {
		var ret string
		return ret
	}
	return *o.Secret.Get()
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookCreate) GetSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Secret.Get(), o.Secret.IsSet()
}

// HasSecret returns a boolean if a field has been set.
func (o *WebhookCreate) HasSecret() bool {
	if o != nil && o.Secret.IsSet() {
		return true
	}

	return false
}

// SetSecret gets a reference to the given NullableString and assigns it to the Secret field.
func (o *WebhookCreate) SetSecret(v string) {
	o.Secret.Set(&v)
}
// SetSecretNil sets the value for Secret to be an explicit nil
func (o *WebhookCreate) SetSecretNil() {
	o.Secret.Set(nil)
}

// UnsetSecret ensures that no value is present for Secret, not even an explicit nil
func (o *WebhookCreate) UnsetSecret() {
	o.Secret.Unset()
}

func (o WebhookCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["monitor_id"] = o.MonitorId
	toSerialize["url"] = o.Url
	if o.Secret.IsSet() {
		toSerialize["secret"] = o.Secret.Get()
	}
	return toSerialize, nil
}

func (o *WebhookCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"monitor_id",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookCreate := _WebhookCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookCreate)

	if err != nil {
		return err
	}

	*o = WebhookCreate(varWebhookCreate)

	return err
}

type NullableWebhookCreate struct {
	value *WebhookCreate
	isSet bool
}

func (v NullableWebhookCreate) Get() *WebhookCreate {
	return v.value
}

func (v *NullableWebhookCreate) Set(val *WebhookCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookCreate(val *WebhookCreate) *NullableWebhookCreate {
	return &NullableWebhookCreate{value: val, isSet: true}
}

func (v NullableWebhookCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


