/*
ScrapeBadger API

Unified credit-based scraping API. https://docs.scrapebadger.com

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package scrapebadger

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VintedPrice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VintedPrice{}

// VintedPrice Money value. The amount is a decimal string, never a float.
type VintedPrice struct {
	Amount string `json:"amount"`
	CurrencyCode string `json:"currency_code"`
}

type _VintedPrice VintedPrice

// NewVintedPrice instantiates a new VintedPrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVintedPrice(amount string, currencyCode string) *VintedPrice {
	this := VintedPrice{}
	this.Amount = amount
	this.CurrencyCode = currencyCode
	return &this
}

// NewVintedPriceWithDefaults instantiates a new VintedPrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVintedPriceWithDefaults() *VintedPrice {
	this := VintedPrice{}
	return &this
}

// GetAmount returns the Amount field value
func (o *VintedPrice) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *VintedPrice) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *VintedPrice) SetAmount(v string) {
	o.Amount = v
}

// GetCurrencyCode returns the CurrencyCode field value
func (o *VintedPrice) GetCurrencyCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CurrencyCode
}

// GetCurrencyCodeOk returns a tuple with the CurrencyCode field value
// and a boolean to check if the value has been set.
func (o *VintedPrice) GetCurrencyCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrencyCode, true
}

// SetCurrencyCode sets field value
func (o *VintedPrice) SetCurrencyCode(v string) {
	o.CurrencyCode = v
}

func (o VintedPrice) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VintedPrice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount"] = o.Amount
	toSerialize["currency_code"] = o.CurrencyCode
	return toSerialize, nil
}

func (o *VintedPrice) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount",
		"currency_code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVintedPrice := _VintedPrice{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVintedPrice)

	if err != nil {
		return err
	}

	*o = VintedPrice(varVintedPrice)

	return err
}

type NullableVintedPrice struct {
	value *VintedPrice
	isSet bool
}

func (v NullableVintedPrice) Get() *VintedPrice {
	return v.value
}

func (v *NullableVintedPrice) Set(val *VintedPrice) {
	v.value = val
	v.isSet = true
}

func (v NullableVintedPrice) IsSet() bool {
	return v.isSet
}

func (v *NullableVintedPrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVintedPrice(val *VintedPrice) *NullableVintedPrice {
	return &NullableVintedPrice{value: val, isSet: true}
}

func (v NullableVintedPrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVintedPrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


